### ISSUE TITLE
Add client side validations to all fields

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/poa-dapps-keys-generation#10]
One notary on testnet didn't fill their data
- bootnode (Igor Barinov)
- Lillian Chan
![image](https://user-images.githubusercontent.com/424628/29781481-53336576-8be7-11e7-9db9-9b014f7c3272.png)

![image](https://user-images.githubusercontent.com/424628/29781553-8fa56a86-8be7-11e7-8ce5-60813acdc3d0.png)

**Comment by vbaranov** [comment]
Implemented in https://github.com/oraclesorg/poa-dapps-keys-generation/pull/25
